### PR TITLE
Fixed spring-boot detection mechanism when adding spring boot badge (icon) to project.

### PR DESCRIPTION
**Pull request by didiez**
There is still an (small) issue: once the project is detected as spring-boot is not evaluated anymore until netbeans restart. 
Behaviour not changed for performance reasons.

### CODE REVIEW

**Comment by AlexFalappa** [comment]
Currently busy, will take some time to look at this PR, thanks for your patience

**Comment by AlexFalappa** [comment]
@didiez all of your PR merged, thank you so much for your contributions!

**Comment by didiez** [comment]
Thank you for this awesome plugin :+1:

**Comment by didiez** [comment]
@AlexFalappa Is there any ETA for a new plugin release? We could not use the latest plugin release listed in plugin portal due to #168
Thanks!

**Comment by AlexFalappa** [comment]
@didiez I am currently very busy with my job and personal things, I am afraid I will not be able to release a new version before August.

If in real need you can build from master and install it.

**Comment by didiez** [comment]
No problem, we are not in a hurry.

> If in real need you can build from master and install it.
That's exactly what we have been doing :)
Thanks again.

**Pull request merged**
