### PR TITLE
Added Travis config and enable tests.

### PR DESCRIPTION
**Pull request by blackleg**
- Added ```.travis.yml``` file to allow run tests in TravisCI.
- Changed pom to run tests on build.

### CODE REVIEW

**Comment by AlexFalappa** [comment]
@blackleg thank you for your PR!

I think I will however not merge it as a whole but take from it the Travis configuration.

As you may have noticed the unit tests are really poor and cover only parsing and lexing, moreover lexing tests require the build to be modified to be executed (due to manual alteration to integrate the resulting lexer with the NetBeans lexing API). Thus at the moment I would like not to enable automatic execution of tests.

**Comment by blackleg** [comment]
@AlexFalappa I could modify the pull request to remove the changes in the pom file to disable tests.

**Comment by AlexFalappa** [comment]
That would be great, thank you.

**Comment by blackleg** [comment]
@AlexFalappa I removed the changes in pom file.

**Comment by blackleg** [comment]
👍

**Pull request merged**
